### ISSUE TITLE
Cannot create repo from template one with GitHub App credentials

### ISSUE THREAD

**Issue by wyczyn73** [crossplane-contrib/provider-upjet-github#118]
I have configured the providerConfig with the GitHub App credentials. I gave the admin rights to the GitHub App for the repository related permission (also for the Organization just in case). Anyway, when trying to add a new repo from the template one, I'm getting following error (removed organization and repo names):

`async create failed: failed to create the resource: [{0 POST https://api.github.com/repos/<my-organization-here>/<my-template-repo-here>/generate: 422 Could not clone: template repository not found. [{Resource: Field: Code: Message:Could not clone: template repository not found.}]`

The template repo exists and I can do the same when using Personal Access Token as a providerConfig credentials. 

So, it looks like it doesn't work just for repo creation from template (there is no issue if I just want to create empty repo) and GitHub App credentials configured in the providerConfig for some reason...

**Comment by AtzeDeVries** [comment]
For the Personal Access Token, did you create a Fine Grained one or a Classic? The access model is different i believe.

**Comment by wyczyn73** [comment]
For PAT I created classic one and it works correctly. I did't try the fine grained one, as my goal is to use GitHub App credentials. For GitHub App, I've configured the GitHub App private key in the ProviderConfig and it doesn't work when trying to create a repo from the template one. It works if I just want to create a new empty repo.

**Comment by AtzeDeVries** [comment]
Ok, can you maybe post the permissions you gave to the app? Create from template should work i think.

**Comment by wyczyn73** [comment]
Actually I guess much more than needed, as the App has:


Repository permissions:
(all read/write)
 Administration, Actions, Checks, Attestations, Code Scanning alerts, Deployments, Environments, Pull Requests
 
 Organization 
 (all read/write)
 Administration, Custom organization roles, Custom repository roles, Members, Personal access token requests, Personal access tokens
 
 I can test with some other set as needed.

**Comment by AtzeDeVries** [comment]
in this list you are missing content
https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-contents

**Comment by AtzeDeVries** [comment]
From the Terraform docs of Github Provider:

```
Note
When used with GitHub App authentication, even GET requests must have the contents:write permission. Without it, the following arguments will be ignored, leading to unexpected behavior and confusing diffs: allow_merge_commit, allow_squash_merge, allow_rebase_merge, merge_commit_title, merge_commit_message, squash_merge_commit_title and squash_merge_commit_message.
```

https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository

**Comment by wyczyn73** [comment]
Sounds promising, let me to test it today....

**Comment by wyczyn73** [comment]
It works! My bad, I should read the documentation more carefully. Thank you very much for your help. :)

**Comment by AtzeDeVries** [comment]
cool, no prob!
