### ISSUE TITLE
Expected an equals sign

### ISSUE THREAD

**Issue by vfarcic** [crossplane-contrib/provider-upjet-github#77]
If `${{ SOMETHING }}` is used in the `content` field, it fails with the `'observe failed: cannot run refresh: refresh failed: Missing key/value separator: Expected an equals sign ("=") to mark the beginning of the attribute value.'` message.

**Comment by AtzeDeVries** [comment]
In which situation is this? When creating a `repository_file` ?

**Comment by vfarcic** [comment]
Yes. I had that issue when creating Files.

**Comment by AtzeDeVries** [comment]
@vfarcic 

I can replicate the issue with provider v0.10.0 and lower. v0.11.0 just got released (add nofork arch, big update in gh provider) and this resolves this issue for me. So please upgrade to v0.110 and see if this resolves the issue. Thanks!

**Comment by AtzeDeVries** [comment]
closing, stale
